server:
  port: 8002

spring:
  profiles:
    active: stream

eureka:
  client:
    enabled: false

logging:
  level:
    root: INFO

---
spring:
  profiles: cloud
eureka:
  client:
    enabled: true

---
spring:
  profiles: stream
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        execute_task_stream:
          destination: execute_task_stream
          contentType: application/json
        update_task_stream:
          destination: update_task_stream
          contentType: application/json
          group: client_group